<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>SXN.Net.TcpServer.Tests</AssemblyName>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<RootNamespace>SXN.Net</RootNamespace>
		<Company>Stas Sultanov</Company>
		<Copyright>Copyright © 2015 Stas Sultanov</Copyright>
		<Description>A Tcp Server.</Description>
		<Product>.NET Framework Extensions</Product>
		<AssemblyTitle>SXN.Net</AssemblyTitle>
		<AssemblyVersion>255.255.255.255</AssemblyVersion>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<Platform>x64</Platform>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
		<DebugType>pdbonly</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\src\TcpServerCli\TcpServerCli.vcxproj" />
	</ItemGroup>
</Project>