<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>SXN.Net</RootNamespace>
		<AssemblyName>SXN.Net.TcpServer</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Company>Stas Sultanov</Company>
		<Copyright>Copyright © 2015 Stas Sultanov</Copyright>
		<Description>A Tcp Server.</Description>
		<Product>.NET Framework Extensions</Product>
		<AssemblyTitle>SXN.Net</AssemblyTitle>
		<AssemblyVersion>255.255.255.255</AssemblyVersion>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configuration>Debug</Configuration>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
		<OutputPath>bin\x64\Debug\</OutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
		<OutputPath>bin\x64\Release\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<DocumentationFile>bin\x64\Release\SXN.Net.TcpServer.XML</DocumentationFile>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
		<OutputPath>bin\x86\Debug\</OutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
		<OutputPath>bin\x86\Release\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Configuration>Debug</Configuration>
	</PropertyGroup>
</Project>